"""Create dados table

Revision ID: 23ce17873154
Revises: 93897670635c
Create Date: 2024-11-12 19:38:39.644979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ce17873154'
down_revision = '93897670635c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('imagens', sa.String(length=500), nullable=True),
    sa.Column('nome_url', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('descricao', sa.Text(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dados')
    # ### end Alembic commands ###
